runtime: nodejs14

instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: dist/_nuxt
    secure: always
    expiration: '14d'

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always
    expiration: '30d'

  - url: /sw.js
    static_files: dist/sw.js
    upload: dist/sw.js
    secure: always
    expiration: '30d'

  - url: /.*
    script: auto
    secure: always

default_expiration: '7d'

env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'

automatic_scaling:
  min_instances: 0
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
